### PR TITLE
Remove "type" field

### PR DESCRIPTION
**Pull request by danielwerg**
Fixes:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules\markdown-table-cjs\index.js from ...\FILENAME.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in ...\node_modules\markdown-table-cjs\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```
For typescript and ts-node

### CODE REVIEW

**Comment by danielwerg** [comment]
Hmm, not sure why pull request closed. Perhaps because I deleted my fork? @glinda93 if it were you is there a reason?

**Comment by glinda93** [comment]
> Hmm, not sure why pull request closed. Perhaps because I deleted my fork? @glinda93 if it were you is there a reason?

I didn't notice your PR.

Thanks for a PR btw 😄

**Comment by danielwerg** [comment]
> This repo is a forked version in order to support commonJS.

This is why in `package.json` field `type` should be either removed or value changed to `commonjs` which is default

**Comment by glinda93** [comment]
@danielwerg 
Can you please share your code? When do you get the error?

**Pull request closed without merging**
